version: '3.1'

services:
  jenkins:
    image: jenkins/jenkins:lts # jenkins install From docker hub
    container_name: my_jenkins
    restart: always
    ports:
      - 9090:8080
      - 50000:50000
    volumes:
      - ~/docker-file-share/jenkins:/var/jenkins_home
    environment:
      TZ: "Asia/Seoul"
    network_mode: my-local-network
    cap_add: # 보안 이슈로 추가
      - NET_ADMIN
    privileged: true # 보안 이슈로 추가
