version: '3.3'

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    container_name: my_minio
    environment:
      MINIO_ROOT_USER: adminadmin
      MINIO_ROOT_PASSWORD: adminadmin
    shm_size: 1gb
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /Users/big/docker-file-share/minio:/data