version: '3.1'
services:
  ubuntu:
    image: cscd053/my_ubuntu:0.2
    container_name: architecture-test
    network_mode: my-local-network
    restart: always
    ports:
      - 8082:8082
      - 8083:8083
      - 8084:8084
      - 8085:8085
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
